name: Create zip packages

on:
  release:
    types: [published]

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1
        with:
          files: articlesgoodsearch/
          dest: articlesgoodsearch.zip
      - uses: vimtor/action-zip@v1
        with:
          files: mod_articles_good_search/
          dest: mod_articles_good_search.zip